[defaults]
portfolio_amount = 20000.0
sizing_portfolio_amount = 19250.0
risk_percent = 0.25
market_regime = "SELECTIVE GO"
iex_sizing_price_buffer_percent = 0.25
iex_sizing_price_buffer_min = 0.05
iex_sizing_price_buffer_max = 0.10
